name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
# a new push on the same branch cancels the in-flight run.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
# ----------------------------- Linting -----------------------------
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4

      - name: Run Linter
        run: bash ./scripts/github/linux/lint.sh

# ----------------------------- Building Linux -----------------------------
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ runner.os }}-ccache

      - name: Configure CMake (Linux)
        run: bash ./scripts/github/linux/config_build.sh

      - name: Build (Linux)
        run: bash ./scripts/github/linux/build.sh

      - name: Upload Linux test binary
        uses: actions/upload-artifact@v4
        with:
          name: linux-test-binary
          path: build-linux/tests/unit_tests
          if-no-files-found: error
          retention-days: 1

# ----------------------------- Building Windows -----------------------------
  build-win:
    runs-on: windows-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Enable MSVC developer command prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake (Windows)
        run: .\scripts\github\windows\config_build.ps1

      - name: Build (Windows)
        run: .\scripts\github\windows\build.ps1

      - name: Upload Windows test binary
        uses: actions/upload-artifact@v4
        with:
          name: windows-test-binary
          path: build/tests/unit_tests.exe
          if-no-files-found: error
          retention-days: 1

# ----------------------------- Testing Linux -----------------------------
  test-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build-linux
    steps:
      - uses: actions/checkout@v4

      - name: Download Linux test binary
        uses: actions/download-artifact@v4
        with:
          name: linux-test-binary
          path: build-linux/tests/

      - name: Configure Test Environment (Linux)
        run: bash ./scripts/github/linux/config_test.sh

      - name: Run Google Tests (Linux)
        run: bash ./scripts/github/linux/test.sh

# ----------------------------- Testing Windows -----------------------------
  test-win:
    runs-on: windows-latest
    timeout-minutes: 10
    needs: build-win
    steps:
      - uses: actions/checkout@v4

      - name: Download Windows test binary
        uses: actions/download-artifact@v4
        with:
          name: windows-test-binary
          path: build/

      - name: Run Google Tests (Windows)
        run: .\scripts\github\windows\test.ps1
